FROM python:3.9
WORKDIR /usr/app
ENV PYTHONUNBUFFERED=1
RUN apt update && \
    apt-get -y install netcat-traditional
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . /usr/app
RUN chmod +x entrypoint.sh
ENTRYPOINT ["/usr/app/entrypoint.sh"]